### ISSUE TITLE
Register language

### ISSUE THREAD

**Issue by lucianopf** [darakeon/dfm#41]
There's mixed language at the register form:

![screen shot 2018-12-17 at 17 34 04](https://user-images.githubusercontent.com/8251208/50110693-09ea3b80-0222-11e9-9b29-30f9bdcb97c6.png)

**Comment by darakeon** [comment]
https://github.com/darakeon/dfm/blob/master/docs/TASKS.md#4133-ant-5

**Comment by darakeon** [comment]
@lucianopf , can you check if the bug is gone? My browsers didn't screw it, I couldn't test.

**Comment by lucianopf** [comment]
![lucas](https://user-images.githubusercontent.com/8251208/64613870-90950900-d3ad-11e9-81f2-2cc31b2f60ad.png)

:clap: its working now! :tada:
